# Generated by Django 4.2.4 on 2023-08-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Автор")),
                (
                    "text_comments",
                    models.TextField(max_length=2000, verbose_name="Текст комментаря"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                        verbose_name="Публікація",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коментар",
                "verbose_name_plural": "Коментарі",
            },
        ),
    ]
